import localFont from 'next/font/local'
import './globals.css'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const myFont = localFont({
  src:'./IRANSansWeb(FaNum).ttf',
  display: 'swap'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir='rtl'>
      <body className={`${myFont.className} bg-customWhite p-3`}>{children}</body>
    </html>
  )
}
